<?php

/*
 * Kyanite main classes, declarations, and configuration.
 * Please do not edit this file, or you may experience instability.
 * Instead, edit config.php
 * The Kyanite Project - https://github.com/Cydrobolt/kyanite
 */

$debug = 0;
$headers = apache_request_headers();

require_once 'config.php';

function autoloader($class) {
    include $class . '.php';
}

spl_autoload_register('autoloader');

session_start();

$hp = "awk3u23987akl278o6aiwo3njs7sj4cnj47aj383aw34a232f179edac904d6e2b";
//connect to mysql with $mysqli variable
$mysqli = new mysqli($host, $user, $passwd, $db) or die("Error : Could not establish database connection");

//SQL Functions
//Sanitize input when using sqlrun!
function sqlrun($query) {
    global $mysqli;
    $queryrs = $query;
    $resultrs = $mysqli->query($queryrs) or die("ERROR in $query && the error is" . $mysqli->error);
    return true;
}

function sqlex($table, $rowf, $where, $wval) {
    global $mysqli; //Import var into function
//Sanitize strings
    $rowfs = $mysqli->real_escape_string($rowf);
    $tables = $mysqli->real_escape_string($table);
    $wheres = $mysqli->real_escape_string($where);
    $wvals = $mysqli->real_escape_string($wval);

    $query = "SELECT $rowfs FROM $tables WHERE $wheres='$wvals'";
    $result = $mysqli->query($query) or showerror();
    $numrows = $result->num_rows;
    if (!$numrows) {
        return false;
    } else {
        return true;
    }
}

function sqlfetch($table, $rowf, $where, $wval) {
    global $mysqli;

    $rowfs = $mysqli->real_escape_string($rowf);
    $tables = $mysqli->real_escape_string($table);
    $wheres = $mysqli->real_escape_string($where);
    $wvals = $mysqli->real_escape_string($wval);

    $query = "SELECT $rowfs FROM $tables WHERE $wheres='$wvals'";
    $result = $mysqli->query($query) or showerror();
    $row = mysqli_fetch_assoc($result);
    return $row[$rowf];
}

function showerror() {
    global $debug;
    global $mysqli;
    echo "There seems to be a problem :'( *sniff* . Click > <a href='http://webchat.freenode.net/?channels=polr'>here</a> contact an administrator.";
    if ($debug == 1) {
        echo "<br>Error:<br>";
        echo $mysqli->error;
    }
    die();
}

function filterurl($url) {
    if (!filter_var($url, FILTER_VALIDATE_URL, FILTER_FLAG_HOST_REQUIRED)) {
        return false;
    } else {
        return true;
    }
}

function filteremail($email) {
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        return false;
    } else {
        return true;
    }
}

function log($msg) {
    $data = $msg;
    $file = "kyanite.log";
    $handle = fopen($file, 'a');
    if (fwrite($handle, $data) === FALSE) {
        //unable to log :'(
    }
    fclose($handle);
}
